### PR TITLE
Fix project adding to feature

### PR DESCRIPTION
**Pull request by SOVALINUX**
Quite critical bug for me, could you please make a release after that?

### CODE REVIEW

**Comment by lburgazzoli** [comment]
Hi,
the release was not intended sorry for that, I'm testing release to gradle's plugin portal.

I've changed the behavior of getProjectDescriptors because the plugin does not work anymore for very simple projects, like:

```gradle
buildscript {
  repositories {
    mavenLocal()
  }
  dependencies {
    classpath "com.github.lburgazzoli:gradle-karaf-features-plugin:2.9.6-SNAPSHOT"
  }
}

apply plugin: "java"
apply plugin: "maven"
apply plugin: "com.github.lburgazzoli.karaf.features"

group               = 'com.github.lburgazzoli'
version             = '1.0.0'
sourceCompatibility = '1.8'
targetCompatibility = '1.8'

repositories {
    mavenLocal()
    mavenCentral()
    jcenter()
}

dependencies {
    compile("org.slf4j:slf4j-api:1.7.13") { transitive = false }
    compile("org.slf4j:slf4j-ext:1.7.13") { transitive = false }
}

karafFeatures {
    name       = project.name
    xsdVersion = '1.3.0'
    outputFile = null

    repository 'mvn:group/dependent-feature/1.2.3/xml/features'
    repository 'mvn:group/artifact/1.1.1/xml/features'

    features {
        'main' {
            description = 'Main feature'
        }
    }
}
```

The features resulting is the one below which is wrong as it does not include any dependence declared in the project:

```xml
<features xmlns='http://karaf.apache.org/xmlns/features/v1.3.0' name='gradle-karaf-features-plugin-examples'>
  <repository>mvn:group/dependent-feature/1.2.3/xml/features</repository>
  <repository>mvn:group/artifact/1.1.1/xml/features</repository>
  <feature name='main' version='1.0.0' description='Main feature' />
</features>
```

But then I've noticed that it breaks your tests. 
I've amended "Simple project" so that it fails (before it was an useful test), can you have a look ?

**Comment by lburgazzoli** [comment]
I've partially fixed it via 364aa3bd6afa37f66a5e01791338dc1bb548df5e, can you check if it break any of your requirements ?

**Comment by SOVALINUX** [comment]
Hi, released version 2.9.6 works fine for me. 
Quite weird example above for me. I'm right that project doesn't have any target jar file, so we shouldn't add it as a bundle?
Looks like we need to add some check about generated artifact in project.

**Comment by lburgazzoli** [comment]
I think we are fine :-) maven need to be instructed to include the project bundle as it is supposed to be used in a separate subproject

**Pull request closed without merging**
