### PR TITLE
Exclude transitive dependencies support added

### PR DESCRIPTION
**Pull request by SOVALINUX**
It fixes issue #11 
Actually it my first code in Groovy, so sorry in advance for silly mistakes

Backward compatibility saved for feature descriptor

Some debug information added (it really helped me understood what's going on)

Readme updated with some examples

### CODE REVIEW

**Comment by SOVALINUX** [comment]
Luca, could you please orient me when you can find some time to review this request?
I'm just thinking about to release it to our corporate network or wait for the main stream

**Comment by lburgazzoli** [comment]
Hope to have a look by tomorrow, sorry for the delay.

**Comment by lburgazzoli** [comment]
I do not like this syntax as it is misleading : 

```groovy
   project(project(':subproject1'))
    project {
        project = project('subproject2')
        excludeTransitiveDependencies = true //false by default
   }
```

I would like something like:

```groovy
   project(':subproject1') {
       dependencies {
           transitive = false
       }
   }
```

This should be a shortcut to avoid writing your own custom configuration with transitive dependencies excluded.

Can you implement it ?

**Comment by SOVALINUX** [comment]
Okay, I'll try to implement it
And question about backward compatibility
currently the only working way is to write
```
project(project(':subproject1'))
```
It because method project takes one argument of type Project

Should I break this approach?

**Comment by lburgazzoli** [comment]
Yes break it, I will highlight it in the documentation :-)

**Comment by SOVALINUX** [comment]
I've updated DSL, it even backward compatible

**Comment by lburgazzoli** [comment]
Can you add your name to the @author tag on the files you have worked on? :-)

**Comment by lburgazzoli** [comment]
Thank you for the PR

**Pull request merged**
